image:
  #repository: forgerock-docker-public.bintray.io/ds
  repository: gcr.io/engineering-devops/ds
  tag: 6.5.0-M0
  pullPolicy: Always
  
gcs:
  enabled: true
  bucket: gs://forgeops/dj-backup/m-cluster

nfs:
  server: 10.191.193.66
  path: /export

backup:
  pvcName: ds-backup
  storageSize: 100Gi

createPVC: true

slackUrl: undefined
