image:
  #repository: forgerock-docker-public.bintray.io/ds
  repository: gcr.io/engineering-devops/ds
  tag: 6.5.0-M0
  pullPolicy: Always

instance: configstore

resources:
  limits:
    memory: 1Gi
  requests:
    memory: 1Gi

replicas: 2

topologyKey: "failure-domain.beta.kubernetes.io/zone"

podAntiAffinity: hard